#!/usr/bin/env python3
"""Generate the inline icon sprite in app/static/index.html from Phosphor.

The founder UI has no build step (docs/10), so the sprite ships inline in the
page. This script is how it is regenerated: it reads the vendored Phosphor
subset in app/static/vendor/icons/phosphor/ and rewrites the block between the
sprite markers in place. Same pattern as vendor/pdfjs — the artwork is
vendored, the output is committed, nothing is fetched at runtime.

Adding an icon: add a row to ICONS, copy the Phosphor SVG into the vendor dir
(`python scripts/build_icons.py --list-missing` tells you which), re-run.

    python scripts/build_icons.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "app" / "static" / "index.html"
VENDOR = ROOT / "app" / "static" / "vendor" / "icons" / "phosphor"

BEGIN = "<!-- @sprite:begin -->"
END = "<!-- @sprite:end -->"

# semantic name (what the UI asks for)  ->  Phosphor "regular" icon name
ICONS: dict[str, str] = {
    # composer + chat
    "send": "arrow-up",
    "mic": "microphone",
    "waveform": "waveform",
    "paperclip": "paperclip",
    "chat": "chat-circle",
    # header + chrome
    "plug": "plugs",
    "refresh": "arrows-clockwise",
    "sun": "sun",
    "moon": "moon",
    "plus": "plus",
    "minus": "minus",
    "close": "x",
    "search": "magnifying-glass",
    "chev-left": "caret-left",
    "chev-right": "caret-right",
    "board": "kanban",
    "clipboard": "clipboard-text",
    # status
    "check": "check",
    "alert": "warning",
    "flag": "flag",
    "star": "star",
    "sparkle": "sparkle",
    "clock": "clock",
    "pause": "pause",
    "shield": "shield-check",
    "compass": "compass",
    "target": "target",
    "pencil": "note-pencil",
    "trash": "trash",
    # documents
    "download": "download-simple",
    "eye": "eye",
    "file-doc": "file-doc",
    "file-sheet": "file-xls",
    "file-slides": "file-ppt",
    "file-pdf": "file-pdf",
    # connectors (neutral marks — submission rules forbid third-party logos)
    "cloud-up": "cloud-arrow-up",
    "inbox": "envelope-simple",
    "calendar": "calendar-blank",
    "globe": "globe-simple",
    "code": "code",
    "link": "link-simple",
    "external": "arrow-square-out",
}

INNER = re.compile(r"<svg[^>]*>(.*)</svg>", re.S)


def symbol(sem: str, phos: str) -> str:
    src = VENDOR / f"{phos}.svg"
    if not src.exists():
        raise SystemExit(
            f"missing {src.relative_to(ROOT)} — copy it from @phosphor-icons/core "
            f"assets/regular/{phos}.svg"
        )
    m = INNER.search(src.read_text(encoding="utf-8"))
    if not m:
        raise SystemExit(f"could not parse {src}")
    body = re.sub(r"\s+", " ", m.group(1)).strip()
    return f'  <symbol id="i-{sem}" viewBox="0 0 256 256">{body}</symbol>'


def main() -> int:
    if "--list-missing" in sys.argv:
        missing = [p for p in ICONS.values() if not (VENDOR / f"{p}.svg").exists()]
        print("\n".join(missing) if missing else "nothing missing")
        return 0

    body = "\n".join(symbol(sem, phos) for sem, phos in ICONS.items())
    sprite = (
        f'{BEGIN}\n'
        f'<!-- Generated by scripts/build_icons.py from the vendored Phosphor subset\n'
        f'     (MIT, app/static/vendor/icons/phosphor/LICENSE). Do not hand-edit:\n'
        f'     add a row to ICONS in that script and re-run. Spec: docs/16 §5. -->\n'
        f'<svg id="sprite" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false">\n'
        f'{body}\n'
        f'</svg>\n'
        f'{END}'
    )

    html = INDEX.read_text(encoding="utf-8")
    if BEGIN not in html or END not in html:
        raise SystemExit(f"sprite markers not found in {INDEX}")
    start, end = html.index(BEGIN), html.index(END) + len(END)
    INDEX.write_text(html[:start] + sprite + html[end:], encoding="utf-8")
    print(f"sprite rebuilt: {len(ICONS)} icons from Phosphor regular")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
