#!/usr/bin/env python3
"""Generate every Co-Founder brand asset from one geometric source.

The mark ("Counterpart") is two identical brackets, rotationally symmetric
about the centre: each holds two sides of a frame that neither closes alone.
Because the halves are separate strokes, the second one can carry `--attn`
when a founder decision is waiting (docs/16 §2.1 — amber means *you are
needed*, and nothing else).

Same contract as scripts/build_icons.py: the artwork is generated, the output
is committed, nothing is fetched at runtime. Do not hand-edit the generated
files — change the constants here and re-run.

    python scripts/build_brand.py

Needs `fonttools` and `cairosvg` (dev-only, see requirements-dev.txt). The
logotype is outlined from IBM Plex Sans SemiBold (SIL Open Font License 1.1,
IBM). Only the outlines travel into the artwork; no font file ships, and no
webfont is linked — docs/16 §3.1 forbids that.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATIC = ROOT / "app" / "static"
BRAND = STATIC / "brand"

BEGIN = "<!-- @brand:begin -->"
END = "<!-- @brand:end -->"
HTML_TARGETS = (
    STATIC / "index.html",
    STATIC / "hiring.html",
    STATIC / "login.html",
)

# --------------------------------------------------------------------------
# The mark. Two brackets on a 100×100 grid; artwork occupies 13…87 in both
# axes, so the drawn box is a true square with 13 units of breathing room.
# Rotating the whole thing 180° about (50,50) maps each path onto the other.
# --------------------------------------------------------------------------
MARK_AGENT = "M20 80L20 20L64 20"
MARK_FOUNDER = "M80 20L80 80L36 80"
MARK_STROKE = 14
MARK_BOX = 74.0  # drawn extent inside the 100-unit viewBox
MARK_INSET = 13.0

WORDMARK_TEXT = "Co-Founder"
FONT_CANDIDATES = (
    Path.home() / "Library" / "Fonts" / "IBMPlexSans-SemiBold.ttf",
    Path("/Library/Fonts/IBMPlexSans-SemiBold.ttf"),
    Path("/usr/share/fonts/truetype/ibm-plex/IBMPlexSans-SemiBold.ttf"),
)
TRACKING = -0.018  # em, tightened for display sizes

# docs/16 §2.1 semantic tokens, resolved per theme.
DARK = {"ground": "#090B10", "tile": "#12151D", "mark": "#6E9BFF",
        "ink": "#E9ECF4", "ink3": "#7C8599", "attn": "#F0B341"}
LIGHT = {"ground": "#EFF2F7", "tile": "#FFFFFF", "mark": "#2F5BD0",
         "ink": "#161B26", "ink3": "#646D80", "attn": "#B8830F"}

GENERATED = "Generated by scripts/build_brand.py — do not hand-edit."


# --------------------------------------------------------------------------
# logotype outlines
# --------------------------------------------------------------------------
def _kerning(font, wanted: set[str]) -> dict[tuple[str, str], int]:
    """Pull horizontal kerning for the pairs we actually set."""
    pairs: dict[tuple[str, str], int] = {}
    if "GPOS" not in font:
        return pairs

    def advance(value) -> int:
        return getattr(value, "XAdvance", 0) or 0 if value else 0

    def walk(subtables):
        for st in subtables:
            if getattr(st, "LookupType", None) == 9 or st.__class__.__name__ == "ExtensionPos":
                walk([st.ExtSubTable])
                continue
            fmt = getattr(st, "Format", None)
            if fmt == 1:
                for i, first in enumerate(st.Coverage.glyphs):
                    if first not in wanted:
                        continue
                    for rec in st.PairSet[i].PairValueRecord:
                        if rec.SecondGlyph in wanted and advance(rec.Value1):
                            pairs[(first, rec.SecondGlyph)] = advance(rec.Value1)
            elif fmt == 2:
                c1, c2 = st.ClassDef1.classDefs, st.ClassDef2.classDefs
                for first in st.Coverage.glyphs:
                    if first not in wanted:
                        continue
                    row = st.Class1Record[c1.get(first, 0)]
                    for second in wanted:
                        try:
                            rec = row.Class2Record[c2.get(second, 0)]
                        except IndexError:
                            continue
                        if advance(rec.Value1):
                            pairs[(first, second)] = advance(rec.Value1)

    for lookup in font["GPOS"].table.LookupList.Lookup:
        if lookup.LookupType in (2, 9):
            walk(lookup.SubTable)
    return pairs


class Logotype:
    """The outlined wordmark, normalised so its ink starts at (0, 0)."""

    def __init__(self, path: str, width: float, height: float, cap: float) -> None:
        self.path, self.width, self.height, self.cap = path, width, height, cap

    @property
    def baseline(self) -> float:
        """Distance from the top of the ink to the baseline (no descenders)."""
        return self.height


def wordmark(cap: float) -> Logotype:
    """Outline WORDMARK_TEXT at the given cap height, ink-tight to the origin."""
    from fontTools.pens.boundsPen import BoundsPen
    from fontTools.pens.svgPathPen import SVGPathPen
    from fontTools.pens.transformPen import TransformPen
    from fontTools.ttLib import TTFont

    src = next((p for p in FONT_CANDIDATES if p.exists()), None)
    if src is None:
        raise SystemExit(
            "IBM Plex Sans SemiBold not found. Install it (https://github.com/IBM/plex,\n"
            "SIL OFL 1.1) or point FONT_CANDIDATES at a copy."
        )
    font = TTFont(src)
    upem = font["head"].unitsPerEm
    scale = cap / font["OS/2"].sCapHeight
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()
    names = [cmap[ord(ch)] for ch in WORDMARK_TEXT]
    kern = _kerning(font, set(names))
    track = TRACKING * upem

    def run(pen, dx: float, dy: float) -> None:
        x = 0.0
        for i, name in enumerate(names):
            glyphs[name].draw(
                TransformPen(pen, (scale, 0, 0, -scale, x * scale + dx, dy))
            )
            x += glyphs[name].width + track
            if i + 1 < len(names):
                x += kern.get((name, names[i + 1]), 0)

    # Measure the real ink, not the advance box: side bearings are not part of
    # a logotype, and the lockup spacing is set optically below.
    probe = BoundsPen(glyphs)
    run(probe, 0.0, 0.0)
    left, top, right, bottom = probe.bounds

    pen = SVGPathPen(glyphs)
    run(pen, -left, -top)
    # Two decimals at cap height 100 is finer than any raster we produce, and
    # it keeps the inlined path near 4 KB instead of 12 KB on three pages.
    # (SVGPathPen only grew an `ntos` hook after the pinned fontTools.)
    path = re.sub(r"-?\d+\.\d+",
                  lambda m: f"{float(m.group()):.2f}".rstrip("0").rstrip(".") or "0",
                  pen.getCommands())
    return Logotype(path, right - left, bottom - top, cap)


# --------------------------------------------------------------------------
# svg builders
# --------------------------------------------------------------------------
def mark_group(colour: str = "currentColor", second: str | None = None) -> str:
    return (
        f'<g fill="none" stroke-width="{MARK_STROKE}" stroke-linejoin="round" '
        f'stroke-linecap="butt">'
        f'<path d="{MARK_AGENT}" stroke="{colour}"/>'
        f'<path d="{MARK_FOUNDER}" stroke="{second or colour}"/>'
        f"</g>"
    )


def mark_svg() -> str:
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" '
        f'role="img" aria-label="Co-Founder">\n'
        f"  <!-- {GENERATED} -->\n"
        f"  {mark_group()}\n"
        f"</svg>\n"
    )


FAVICON_FILL = 0.78   # a tab strip is 16 px; the mark fills more of the tile there


def favicon_svg() -> str:
    """Rounded tile + mark, with the per-theme style block the old file got right."""
    drawn = 32 * FAVICON_FILL
    scale = drawn / MARK_BOX
    off = (32 - drawn) / 2 - MARK_INSET * scale
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" role="img">\n'
        "  <title>Co-Founder</title>\n"
        f"  <!-- {GENERATED} -->\n"
        "  <style>\n"
        f'    .tile {{ fill: {DARK["tile"]}; }}\n'
        f'    .mark {{ stroke: {DARK["mark"]}; }}\n'
        "    @media (prefers-color-scheme: light) {\n"
        f'      .tile {{ fill: {LIGHT["tile"]}; }}\n'
        f'      .mark {{ stroke: {LIGHT["mark"]}; }}\n'
        "    }\n"
        "  </style>\n"
        '  <rect class="tile" width="32" height="32" rx="7"/>\n'
        f'  <g class="mark" fill="none" stroke-width="{MARK_STROKE}"'
        f' stroke-linejoin="round" stroke-linecap="butt"'
        f' transform="translate({off:.3f} {off:.3f}) scale({scale:.5f})">\n'
        f'    <path d="{MARK_AGENT}"/>\n'
        f'    <path d="{MARK_FOUNDER}"/>\n'
        "  </g>\n"
        "</svg>\n"
    )


CAP_TO_MARK = 0.76     # logotype cap height as a fraction of the drawn mark
GAP_TO_MARK = 0.32     # clear space between mark and logotype


def _lockup_layout(logo: Logotype) -> dict[str, float]:
    """Place mark and logotype so the cap band centres on the mark."""
    mark_h = logo.cap / CAP_TO_MARK
    gap = mark_h * GAP_TO_MARK
    return {
        "mark_h": mark_h,
        "scale": mark_h / MARK_BOX,
        "word_x": mark_h + gap,
        # baseline sits at ink bottom; centre the cap band, not the ascender.
        "word_y": mark_h / 2 - logo.baseline + logo.cap / 2,
        "width": mark_h + gap + logo.width,
    }


def lockup_svg(logo: Logotype) -> str:
    """Mark + logotype, sized so the two read as one object."""
    L = _lockup_layout(logo)
    inset = MARK_INSET * L["scale"]
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'viewBox="0 0 {L["width"]:.2f} {L["mark_h"]:.2f}" '
        f'role="img" aria-label="Co-Founder">\n'
        f"  <title>Co-Founder</title>\n"
        f"  <!-- {GENERATED} -->\n"
        "  <style>\n"
        f'    .mark {{ stroke: {DARK["mark"]}; }} .word {{ fill: {DARK["ink"]}; }}\n'
        "    @media (prefers-color-scheme: light) {\n"
        f'      .mark {{ stroke: {LIGHT["mark"]}; }} .word {{ fill: {LIGHT["ink"]}; }}\n'
        "    }\n"
        "  </style>\n"
        f'  <g class="mark" fill="none" stroke-width="{MARK_STROKE}" stroke-linejoin="round"'
        f' stroke-linecap="butt"'
        f' transform="translate({-inset:.3f} {-inset:.3f}) scale({L["scale"]:.5f})">\n'
        f'    <path d="{MARK_AGENT}"/>\n'
        f'    <path d="{MARK_FOUNDER}"/>\n'
        "  </g>\n"
        f'  <path class="word" transform="translate({L["word_x"]:.2f} {L["word_y"]:.2f})"'
        f' d="{logo.path}"/>\n'
        "</svg>\n"
    )


def lockup_css(logo: Logotype) -> str:
    """Lockup geometry as CSS, derived from the same constants as the artwork.

    A page sets one thing — `--brand-size`, the *drawn* height of the mark —
    plus colour. Everything else follows, so an in-app lockup can never drift
    from brand/lockup.svg. The negative margin cancels the mark's own inset,
    which would otherwise widen the gap by 13/74 of the mark.
    """
    inset = MARK_INSET / MARK_BOX
    box = MARK_BOX / 100
    word = CAP_TO_MARK * (logo.height / logo.cap)
    size = "var(--brand-size, 20px)"
    return (
        f".brand-lockup{{display:inline-flex;align-items:center;"
        f"gap:calc({size} * {GAP_TO_MARK})}}"
        f".brand-mark{{width:calc({size} / {box});aspect-ratio:1;flex:none}}"
        f".brand-lockup>.brand-mark{{margin-right:calc({size} * -{inset:.5f})}}"
        f".brand-word{{height:calc({size} * {word:.4f});"
        f"aspect-ratio:{logo.width:.2f}/{logo.height:.2f};flex:none}}"
    )


def sprite_block(logo: Logotype) -> str:
    """The <symbol> pair the product pages consume, so colour stays in CSS."""
    return (
        f"{BEGIN}\n"
        f"<!-- {GENERATED} Regenerate with `python scripts/build_brand.py`.\n"
        f"     Colour comes from the use site: .brand-mark takes --accent,\n"
        f"     .brand-word takes --ink-1. Spec: docs/16 §5.6. -->\n"
        f"<style>{lockup_css(logo)}</style>\n"
        '<svg id="brandmarks" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"'
        ' focusable="false" style="position:absolute;width:0;height:0;overflow:hidden">\n'
        f'<symbol id="brand-mark" viewBox="0 0 100 100">{mark_group()}</symbol>\n'
        f'<symbol id="brand-word" viewBox="0 0 {logo.width:.2f} {logo.height:.2f}">'
        f'<path fill="currentColor" d="{logo.path}"/></symbol>\n'
        "</svg>\n"
        f"{END}"
    )


def tile_png_svg(size: int, bg: str, radius: float, fill_ratio: float,
                 colour: str) -> str:
    """One square raster source: optional rounded tile plus a centred mark."""
    drawn = size * fill_ratio
    scale = drawn / MARK_BOX
    off = (size - drawn) / 2 - MARK_INSET * scale
    rect = (
        f'<rect width="{size}" height="{size}" rx="{radius:.2f}" fill="{bg}"/>'
        if bg else ""
    )
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" '
        f'viewBox="0 0 {size} {size}">{rect}'
        f'<g fill="none" stroke="{colour}" stroke-width="{MARK_STROKE}" '
        f'stroke-linejoin="round" stroke-linecap="butt" '
        f'transform="translate({off:.3f} {off:.3f}) scale({scale:.5f})">'
        f'<path d="{MARK_AGENT}"/><path d="{MARK_FOUNDER}"/></g></svg>'
    )


def og_svg(logo: Logotype) -> str:
    """1200×630 link preview on the dark ground."""
    W, H = 1200, 630
    L = _lockup_layout(logo)
    scale = 148.0 / L["mark_h"]          # drawn mark height on the card
    x0 = (W - L["width"] * scale) / 2
    y0 = (H - L["mark_h"] * scale) / 2 - 34
    mark_scale = L["scale"] * scale
    inset = MARK_INSET * mark_scale
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" '
        f'viewBox="0 0 {W} {H}">'
        f'<rect width="{W}" height="{H}" fill="{DARK["ground"]}"/>'
        f'<g fill="none" stroke="{DARK["mark"]}" stroke-width="{MARK_STROKE}" '
        f'stroke-linejoin="round" stroke-linecap="butt" '
        f'transform="translate({x0 - inset:.2f} {y0 - inset:.2f}) scale({mark_scale:.5f})">'
        f'<path d="{MARK_AGENT}"/><path d="{MARK_FOUNDER}"/></g>'
        f'<path fill="{DARK["ink"]}" transform="translate('
        f'{x0 + L["word_x"] * scale:.2f} {y0 + L["word_y"] * scale:.2f}) '
        f'scale({scale * 1.0:.5f})" d="{logo.path}"/>'
        f'<text x="{W / 2}" y="{y0 + L["mark_h"] * scale + 86:.0f}" text-anchor="middle" '
        f'font-family="IBM Plex Sans, ui-sans-serif, sans-serif" font-size="30" '
        f'font-weight="400" fill="{DARK["ink3"]}">'
        f"The agent does the work; founders keep the judgment."
        f"</text></svg>"
    )


MANIFEST = {
    "name": "Co-Founder",
    "short_name": "Co-Founder",
    "description": "A persistent AI operating partner for founders.",
    "start_url": "/",
    "display": "standalone",
    "background_color": DARK["ground"],
    "theme_color": DARK["ground"],
    "icons": [
        {"src": "/favicon.svg", "sizes": "any", "type": "image/svg+xml"},
        {"src": "/icon-192.png", "sizes": "192x192", "type": "image/png"},
        {"src": "/icon-512.png", "sizes": "512x512", "type": "image/png"},
        {"src": "/icon-maskable-512.png", "sizes": "512x512", "type": "image/png",
         "purpose": "maskable"},
    ],
}


def main() -> int:
    try:
        import cairosvg
    except ImportError:
        raise SystemExit(
            "cairosvg is required to rasterise the icon set:\n"
            "    pip install -r requirements-dev.txt"
        ) from None

    logo = wordmark(cap=100.0)
    BRAND.mkdir(parents=True, exist_ok=True)

    written: list[str] = []

    def write(path: Path, text: str) -> None:
        path.write_text(text, encoding="utf-8")
        written.append(str(path.relative_to(ROOT)))

    def raster(path: Path, svg: str, size: int) -> None:
        cairosvg.svg2png(bytestring=svg.encode(), write_to=str(path),
                         output_width=size, output_height=size)
        written.append(str(path.relative_to(ROOT)))

    write(BRAND / "mark.svg", mark_svg())
    write(BRAND / "lockup.svg", lockup_svg(logo))
    write(STATIC / "favicon.svg", favicon_svg())

    # Apple wants full-bleed and opaque — iOS applies its own corner radius.
    raster(STATIC / "apple-touch-icon.png",
           tile_png_svg(180, DARK["tile"], 0, 0.62, DARK["mark"]), 180)
    # `purpose: any` icons are shown as drawn, so they carry the tile shape.
    for size in (192, 512):
        raster(STATIC / f"icon-{size}.png",
               tile_png_svg(size, DARK["tile"], size * 0.22, 0.62, DARK["mark"]), size)
    # Maskable: everything must survive a circular crop at 80% of the canvas,
    # so the square mark can be at most 0.8/√2 ≈ 56.5% wide.
    raster(STATIC / "icon-maskable-512.png",
           tile_png_svg(512, DARK["ground"], 0, 0.52, DARK["mark"]), 512)

    cairosvg.svg2png(bytestring=og_svg(logo).encode(),
                     write_to=str(STATIC / "og-image.png"),
                     output_width=1200, output_height=630)
    written.append("app/static/og-image.png")

    write(STATIC / "site.webmanifest", json.dumps(MANIFEST, indent=2) + "\n")

    block = sprite_block(logo)
    for target in HTML_TARGETS:
        html = target.read_text(encoding="utf-8")
        if BEGIN not in html or END not in html:
            raise SystemExit(
                f"brand markers not found in {target.relative_to(ROOT)} — add\n"
                f"    {BEGIN}\n    {END}\n"
                "at the top of <body> first."
            )
        start, end = html.index(BEGIN), html.index(END) + len(END)
        target.write_text(html[:start] + block + html[end:], encoding="utf-8")
        written.append(str(target.relative_to(ROOT)))

    print(f"brand rebuilt — logotype {logo.width:.1f}×{logo.height:.1f} at cap {logo.cap:.0f}")
    for name in written:
        print(f"  {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
